export const TURKISH_UNIVERSITIES = [
  "Abant İzzet Baysal Üniversitesi",
  "Abdullah Gül Üniversitesi",
  "Acıbadem Mehmet Ali Aydınlar Üniversitesi",
  "Adana Alparslan Türkeş Bilim ve Teknoloji Üniversitesi",
  "Adıyaman Üniversitesi",
  "Afyon Kocatepe Üniversitesi",
  "Afyonkarahisar Sağlık Bilimleri Üniversitesi",
  "Ağrı İbrahim Çeçen Üniversitesi",
  "Akdeniz Üniversitesi",
  "Aksaray Üniversitesi",
  "Alanya Alaaddin Keykubat Üniversitesi",
  "Alanya HEP Üniversitesi",
  "Altınbaş Üniversitesi",
  "Amasya Üniversitesi",
  "Anadolu Üniversitesi",
  "Ankara Hacı Bayram Veli Üniversitesi",
  "Ankara Medipol Üniversitesi",
  "Ankara Müzik ve Güzel Sanatlar Üniversitesi",
  "Ankara Sosyal Bilimler Üniversitesi",
  "Ankara Üniversitesi",
  "Ankara Yıldırım Beyazıt Üniversitesi",
  "Ardahan Üniversitesi",
  "Artvin Çoruh Üniversitesi",
  "Atatürk Üniversitesi",
  "Atılım Üniversitesi",
  "Avrasya Üniversitesi",
  "Aydin Adnan Menderes Üniversitesi",
  "Aydın Üniversitesi",
  "Balıkesir Üniversitesi",
  "Bandırma Onyedi Eylül Üniversitesi",
  "Bartın Üniversitesi",
  "Başkent Üniversitesi",
  "Batman Üniversitesi",
  "Bayburt Üniversitesi",
  "Beykent Üniversitesi",
  "Beykoz Üniversitesi",
  "Bezm-i Alem Vakıf Üniversitesi",
  "Bilecik Şeyh Edebali Üniversitesi",
  "Bilkent Üniversitesi",
  "Bingöl Üniversitesi",
  "Bitlis Eren Üniversitesi",
  "Boğaziçi Üniversitesi",
  "Bolu Abant İzzet Baysal Üniversitesi",
  "Burdur Mehmet Akif Ersoy Üniversitesi",
  "Bursa Teknik Üniversitesi",
  "Bursa Uludağ Üniversitesi",
  "Çağ Üniversitesi",
  "Çanakkale Onsekiz Mart Üniversitesi",
  "Çankaya Üniversitesi",
  "Çankırı Karatekin Üniversitesi",
  "Çukurova Üniversitesi",
  "Demiroğlu Bilim Üniversitesi",
  "Dicle Üniversitesi",
  "Doğu Akdeniz Üniversitesi",
  "Dokuz Eylül Üniversitesi",
  "Düzce Üniversitesi",
  "Ege Üniversitesi",
  "Erciyes Üniversitesi",
  "Erzincan Binali Yıldırım Üniversitesi",
  "Erzurum Teknik Üniversitesi",
  "Eskişehir Osmangazi Üniversitesi",
  "Eskişehir Teknik Üniversitesi",
  "Fatih Sultan Mehmet Vakıf Üniversitesi",
  "Fenerbahçe Üniversitesi",
  "Fırat Üniversitesi",
  "Galatasaray Üniversitesi",
  "Gaziantep İslam Bilim ve Teknoloji Üniversitesi",
  "Gaziantep Üniversitesi",
  "Gebze Teknik Üniversitesi",
  "Giresun Üniversitesi",
  "Gümüşhane Üniversitesi",
  "Hacettepe Üniversitesi",
  "Hakkari Üniversitesi",
  "Haliç Üniversitesi",
  "Harran Üniversitesi",
  "Hatay Mustafa Kemal Üniversitesi",
  "Hitit Üniversitesi",
  "Işık Üniversitesi",
  "İbn Haldun Üniversitesi",
  "İnönü Üniversitesi",
  "İskenderun Teknik Üniversitesi",
  "İstanbul 29 Mayıs Üniversitesi",
  "İstanbul Arel Üniversitesi",
  "İstanbul Atlas Üniversitesi",
  "İstanbul Aydın Üniversitesi",
  "İstanbul Ayvansaray Üniversitesi",
  "İstanbul Bilgi Üniversitesi",
  "İstanbul Bilim Üniversitesi",
  "İstanbul Esenyurt Üniversitesi",
  "İstanbul Galata Üniversitesi",
  "İstanbul Gedik Üniversitesi",
  "İstanbul Gelişim Üniversitesi",
  "İstanbul Kent Üniversitesi",
  "İstanbul Kültür Üniversitesi",
  "İstanbul Medeniyet Üniversitesi",
  "İstanbul Medipol Üniversitesi",
  "İstanbul Nişantaşı Üniversitesi",
  "İstanbul Okan Üniversitesi",
  "İstanbul Rumeli Üniversitesi",
  "İstanbul Sabahattin Zaim Üniversitesi",
  "İstanbul Sağlık ve Teknoloji Üniversitesi",
  "İstanbul Teknik Üniversitesi",
  "İstanbul Ticaret Üniversitesi",
  "İstanbul Topkapı Üniversitesi",
  "İstanbul Üniversitesi",
  "İstanbul Üniversitesi-Cerrahpaşa",
  "İstanbul Yeni Yüzyıl Üniversitesi",
  "İzmir Bakırçay Üniversitesi",
  "İzmir Demokrasi Üniversitesi",
  "İzmir Ekonomi Üniversitesi",
  "İzmir Katip Çelebi Üniversitesi",
  "İzmir Yüksek Teknoloji Enstitüsü",
  "Kadir Has Üniversitesi",
  "Kafkas Üniversitesi",
  "Kapadokya Üniversitesi",
  "Karabük Üniversitesi",
  "Karadeniz Teknik Üniversitesi",
  "Karamanoğlu Mehmetbey Üniversitesi",
  "Kastamonu Üniversitesi",
  "Kayseri Üniversitesi",
  "Kırıkkale Üniversitesi",
  "Kırklareli Üniversitesi",
  "Kırşehir Ahi Evran Üniversitesi",
  "Kilis 7 Aralık Üniversitesi",
  "Kocaeli Üniversitesi",
  "Koç Üniversitesi",
  "Konya Teknik Üniversitesi",
  "Kütahya Dumlupınar Üniversitesi",
  "Kütahya Sağlık Bilimleri Üniversitesi",
  "Lokman Hekim Üniversitesi",
  "Malatya Turgut Özal Üniversitesi",
  "Maltepe Üniversitesi",
  "Manisa Celal Bayar Üniversitesi",
  "Mardin Artuklu Üniversitesi",
  "Marmara Üniversitesi",
  "MEF Üniversitesi",
  "Mersin Üniversitesi",
  "Mimar Sinan Güzel Sanatlar Üniversitesi",
  "Munzur Üniversitesi",
  "Muğla Sıtkı Koçman Üniversitesi",
  "Muş Alparslan Üniversitesi",
  "Necmettin Erbakan Üniversitesi",
  "Nevşehir Hacı Bektaş Veli Üniversitesi",
  "Niğde Ömer Halisdemir Üniversitesi",
  "Nişantaşı Üniversitesi",
  "Ondokuz Mayıs Üniversitesi",
  "Ordu Üniversitesi",
  "Orta Doğu Teknik Üniversitesi",
  "Osmaniye Korkut Ata Üniversitesi",
  "Özyeğin Üniversitesi",
  "Pamukkale Üniversitesi",
  "Piri Reis Üniversitesi",
  "Recep Tayyip Erdoğan Üniversitesi",
  "Sabancı Üniversitesi",
  "Sakarya Uygulamalı Bilimler Üniversitesi",
  "Sakarya Üniversitesi",
  "Samsun Üniversitesi",
  "Selçuk Üniversitesi",
  "Siirt Üniversitesi",
  "Sinop Üniversitesi",
  "Sivas Cumhuriyet Üniversitesi",
  "Sivas Bilim ve Teknoloji Üniversitesi",
  "Süleyman Demirel Üniversitesi",
  "Şırnak Üniversitesi",
  "TED Üniversitesi",
  "Tekirdağ Namık Kemal Üniversitesi",
  "TOBB Ekonomi ve Teknoloji Üniversitesi",
  "Tokat Gaziosmanpaşa Üniversitesi",
  "Toros Üniversitesi",
  "Trakya Üniversitesi",
  "Türk-Alman Üniversitesi",
  "Türk-Japon Bilim ve Teknoloji Üniversitesi",
  "Türkiye-Japonya Bilim ve Teknoloji Üniversitesi",
  "Ufuk Üniversitesi",
  "Uşak Üniversitesi",
  "Üsküdar Üniversitesi",
  "Van Yüzüncü Yıl Üniversitesi",
  "Yaşar Üniversitesi",
  "Yeditepe Üniversitesi",
  "Yıldız Teknik Üniversitesi",
  "Yozgat Bozok Üniversitesi",
  "Yüksek İhtisas Üniversitesi",
  "Zonguldak Bülent Ecevit Üniversitesi",
];

export const TURKISH_DEPARTMENTS: Record<string, string[]> = {
  default: [
    "Acil Yardım ve Afet Yönetimi",
    "Aktüerya ve Risk Yönetimi",
    "Ameliyathane Hizmetleri",
    "Antropoloji",
    "Arkeoloji",
    "Arkeoloji ve Sanat Tarihi",
    "Astronomi ve Uzay Bilimleri",
    "Atatürk İlkeleri ve İnkılap Tarihi",
    "Avrupa Birliği İlişkileri",
    "Avukatlık",
    "Beden Eğitimi ve Spor",
    "Bilgisayar Mühendisliği",
    "Bilgisayar ve Öğretim Teknolojileri Öğretmenliği",
    "Biyokimya",
    "Biyoloji",
    "Biyomedikal Mühendisliği",
    "Biyoteknoloji",
    "Coğrafya",
    "Çevre Mühendisliği",
    "Çevre Yönetimi",
    "Çocuk Gelişimi",
    "Çocuk Sağlığı ve Hastalıkları Hemşireliği",
    "Dil ve Konuşma Terapisi",
    "Diş Hekimliği",
    "Ekonometri",
    "Ekonomi",
    "Ekonomi ve Finans",
    "Eğitim Bilimleri",
    "Elektrik-Elektronik Mühendisliği",
    "Elektronik ve Haberleşme Mühendisliği",
    "Enerji Mühendisliği",
    "Enerji Sistemleri Mühendisliği",
    "Endüstri Mühendisliği",
    "Endüstriyel Tasarım",
    "Eczacılık",
    "Felsefe",
    "Fen Bilgisi Öğretmenliği",
    "Fen Bilimleri",
    "Fizyoterapi ve Rehabilitasyon",
    "Fizik",
    "Fizik Mühendisliği",
    "Finans ve Bankacılık",
    "Fotoğraf ve Video",
    "Gastronomi ve Mutfak Sanatları",
    "Gemi İnşaatı ve Deniz Bilimleri",
    "Gıda Mühendisliği",
    "Grafik Tasarım",
    "Güzel Sanatlar",
    "Havacılık ve Uzay Mühendisliği",
    "Halkla İlişkiler ve Reklamcılık",
    "Halk Sağlığı",
    "Hemşirelik",
    "Hukuk",
    "İç Mimarlık ve Çevre Tasarımı",
    "İktisat",
    "İletişim",
    "İletişim Tasarımı",
    "İlköğretim Matematik Öğretmenliği",
    "İnşaat Mühendisliği",
    "İngiliz Dili ve Edebiyatı",
    "İngilizce Öğretmenliği",
    "İnsan Kaynakları Yönetimi",
    "İşletme",
    "İşletme Mühendisliği",
    "İstatistik",
    "İstatistik ve Bilgisayar Bilimleri",
    "İşaret Dili ve Engelli Çalışmaları",
    "Jeodezi ve Fotogrametri Mühendisliği",
    "Jeofizik Mühendisliği",
    "Jeoloji Mühendisliği",
    "Kimya",
    "Kimya Mühendisliği",
    "Kriminoloji",
    "Lojistik Yönetimi",
    "Makine Mühendisliği",
    "Maliye",
    "Matematik",
    "Matematik Mühendisliği",
    "Matematik Öğretmenliği",
    "Medikal Görüntüleme Teknikleri",
    "Metalurji ve Malzeme Mühendisliği",
    "Mimar",
    "Mimarlık",
    "Mimarlık ve Kentsel Tasarım",
    "Moleküler Biyoloji ve Genetik",
    "Mühendislik Yönetimi",
    "Muhasebe ve Finans Yönetimi",
    "Müzik",
    "Nükleer Enerji Mühendisliği",
    "Nükleer Fizik",
    "Okul Öncesi Öğretmenliği",
    "Ortopedik Protez ve Ortez",
    "Pazar Araştırması ve Tüketici Davranışları",
    "Pazarlama",
    "Psikoloji",
    "Radyo, Televizyon ve Sinema",
    "Reklamcılık",
    "Sağlık Yönetimi",
    "Sağlık Bilişimi",
    "Sanat ve Tasarım",
    "Sanat Tarihi",
    "Siyaset Bilimi ve Kamu Yönetimi",
    "Siyaset Bilimi ve Uluslararası İlişkiler",
    "Sivil Havacılık",
    "Sosyal Hizmet",
    "Sosyoloji",
    "Spor Yönetimi",
    "Su Ürünleri Mühendisliği",
    "Tarih",
    "Tarih Öğretmenliği",
    "Tıbbi Biyoloji",
    "Tıbbi Görüntüleme",
    "Tıbbi Laboratuvar Teknikleri",
    "Tıp",
    "Tekstil Mühendisliği",
    "Turizm İşletmeciliği",
    "Turizm ve Otel İşletmeciliği",
    "Türk Dili ve Edebiyatı",
    "Türkçe Öğretmenliği",
    "Uluslararası İlişkiler",
    "Uluslararası Lojistik ve Taşımacılık",
    "Uluslararası Ticaret ve Lojistik",
    "Uluslararası Ticaret",
    "Uçak Gövde ve Motor Bakımı",
    "Veterinerlik",
    "Yazılım Mühendisliği",
    "Yönetim Bilişim Sistemleri",
    "Yönetim ve Organizasyon",
    "Ziraat Mühendisliği",
  ],
};

export function getDepartments(university: string): string[] {
  return TURKISH_DEPARTMENTS[university] ?? TURKISH_DEPARTMENTS.default;
}
